### ISSUE TITLE
Erro no cálculo de MinutosTrabalhados

### ISSUE THREAD

**Issue by KenjiNishi** [PontoSprint4/br.com.proway.senior.controlePonto#33]
A função de minutos trabalhados não considera nossos "casos 1 e 2" para períodos dos pontos.

**Quando o intervalo de pontos cruza a meia noite o cálculo é feito incorretamente.** 

**Exemplo:**

Ponto 1: 23:00
Ponto 2: 01:00

* Deveria retornar (2*60) minutos trabalhados.

* Estamos recebendo (22*60) minutos trabalhados.

=====

Funções envolvidas para a resolução da Issue:
* tempoEntreRegistros na classe FormatacaoTempo     <----- A ser arrumada
* pontoDentroDoTurno na classe JornadaController     <----- Logica a ser implementada na função anterior

**Comment by gehrkev** [comment]
O problema aparece no método construtor do TurnoDTO onde
`public TurnoDTO(Turno turno) {
...
this.minutosTrabalho = this.horaInicio.until(horaFim, ChronoUnit.MINUTES);
...
}`
(note minutosTrabalho - são minutos esperados do turno, não minutos realizados da jornada) não leva em consideração o método tempoEntreRegistros, que já faz o cálculo corretamente.
O problema é que não podemos chamar tempoEntreRegistros diretamente pois ele recebe LocalDateTime enquanto o TurnoDTO trabalha com LocalTime
Estamos trabalhando nisso na branch turnoMadrugada

**Comment by gehrkev** [comment]
método FormatacaoDeTempo.calculaMinutosEsperadosNoTurno(horaInicio, horaFim) criado resolve o problema do TurnoDTO da madrugada, na cobertura dos testes já diz que foi coberto (sem criarmos um teste próprio), então falta decidir se precisamos testar ainda assim + documentar método

**Comment by KenjiNishi** [comment]
Pull Request Merged!

**Comment by KenjiNishi** [comment]
@gehrkev 

Aqueles comentários foram resolvidos/checados?

**Comment by gehrkev** [comment]
closes #33
@KenjiNishi resolvido, commitado na sprint7
