### ISSUE TITLE
Finalizar testes das classes Service

### ISSUE THREAD

**Issue by KenjiNishi** [PontoSprint4/br.com.proway.senior.controlePonto#41]
# Descrição

Para aumentar a cobertura de testes no nosso sistema ainda é necessário finalizar os testes de JUnit das classes Service Ponto, Turno e Jornada.

# Tarefas

- [x]  Testes do Service Ponto
- [x]  Testes do Service Turno
- [x] Testes do Service Jornada

**Comment by gehrkev** [comment]
ServiceJornada acho que está ok @KenjiNishi ?
