### ISSUE TITLE
Tela de criação e edição de Jornada

### ISSUE THREAD

**Issue by thiagobarbieri** [PontoSprint4/br.com.proway.senior.controlePonto#70]
# Descrição

Telas para criar/editar Jornadas de um Usuário, padronizadas com CSS já utilizada. Alterada a função da tecla retornar para que apareça como principal a tela Marcar Ponto.

# Tarefas

- [x]  Criar pagina de Criação de Jornadas.
- [x]  Criar pagina de Edição de Jornadas.
- [x]  Alterar botão de Retornar da Pagina de Histórico de Jornadas.
- [x]  Alterar botão de Retornar da Pagina de Edição de Ponto.

**Comment by LeonardoPereirajr** [comment]
Providenciado

**Comment by LeonardoPereirajr** [comment]
Providenciado
